require:
  - rubocop-i18n
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisabledByDefault: false
  SuggestExtensions: false
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

# Layout Cops

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

# RSpec Cops

# warning: its raising fake false warning
RSpec/FilePath:
  Enabled: false

# Style Cops

# Helps you transition from mutable string literals to frozen string literals.
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true
  EnforcedStyle: always

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Checks for redundant return expressions.
Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true # allows "return x, y"

# To reactivate!
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false
RSpec/RepeatedExampleGroupBody:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
